version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: technote
    env_file:
      - .env.production
    volumes:
      - .:/var/www
    networks:
      - technote-network

  nginx:
    image: nginx:latest
    container_name: technote_nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - technote-network

  mysql:
    image: mysql:8.0
    container_name: technote_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: task_ms
      MYSQL_ROOT_PASSWORD: kevs.busdev!!
      MYSQL_USER: technote
      MYSQL_PASSWORD: technote.busdev!!
    ports:
      - "3306:3306"
    networks:
      - technote-network

networks:
  technote-network:
